
public class Root
{
    public string type { get; set; }
    public List<int> flags { get; set; }
    public double version { get; set; }
    public string file_type { get; set; }
    public string author { get; set; }
    public string description { get; set; }
    public int num_objects { get; set; }
    public List<List<object>> masters { get; set; }
    public string id { get; set; }
    public object value { get; set; }
    public string global_type { get; set; }
    public string name { get; set; }
    public Data data { get; set; }
    public List<string> rank_names { get; set; }
    public List<Reaction> reactions { get; set; }
    public string sound_path { get; set; }
    public string effect_id { get; set; }
    public string icon { get; set; }
    public string texture { get; set; }
    public string bolt_sound { get; set; }
    public string cast_sound { get; set; }
    public string hit_sound { get; set; }
    public string area_sound { get; set; }
    public Header header { get; set; }
    public string variables { get; set; }
    public string bytecode { get; set; }
    public string text { get; set; }
    public WeatherChances weather_chances { get; set; }
    public List<int> map_color { get; set; }
    public List<List<object>> sounds { get; set; }
    public string script { get; set; }
    public int? index { get; set; }
    public List<Effect> effects { get; set; }
    public string mesh { get; set; }
    public string open_sound { get; set; }
    public string close_sound { get; set; }
    public string enchanting { get; set; }
    public double? encumbrance { get; set; }
    public int? container_flags { get; set; }
    public List<List<object>> inventory { get; set; }
    public int? creature_flags { get; set; }
    public List<string> spells { get; set; }
    public AiData ai_data { get; set; }
    public List<AiPackage> ai_packages { get; set; }
    public List<object> travel_destinations { get; set; }
    public string sound { get; set; }
    public double? scale { get; set; }
    public string race { get; set; }
    public string @class { get; set; }
    public string faction { get; set; }
    public string head { get; set; }
    public string hair { get; set; }
    public int? npc_flags { get; set; }
    public List<BipedObject> biped_objects { get; set; }
    public int? list_flags { get; set; }
    public int? chance_none { get; set; }
    public List<List<object>> items { get; set; }
    public List<List<object>> creatures { get; set; }
    public string region { get; set; }
    public List<Reference> references { get; set; }
    public double? water_height { get; set; }
    public AtmosphereData atmosphere_data { get; set; }
    public string cell { get; set; }
    public List<Point> points { get; set; }
    public List<int> connections { get; set; }
    public int? sound_flags { get; set; }
    public string creature { get; set; }
    public string dialogue_type { get; set; }
    public string info_id { get; set; }
    public string prev_id { get; set; }
    public string next_id { get; set; }
    public int? quest_name { get; set; }
    public List<Filter> filters { get; set; }
    public int? quest_finish { get; set; }
    public int? quest_restart { get; set; }
    public string speaker_id { get; set; }
    public string result { get; set; }
    public string player_faction { get; set; }
    public string speaker_cell { get; set; }
    public string speaker_rank { get; set; }
    public string speaker_class { get; set; }
    public string speaker_faction { get; set; }
}